FROM python:3.12-slim

RUN pip install uv

WORKDIR /app

COPY pyproject.toml uv.lock ./
ENV UV_PROJECT_ENVIRONMENT=/usr/local/
RUN uv sync --locked --no-dev

COPY . ./

ENTRYPOINT [ "python", "/app/KubiScan.py" ]
