FROM python:3.12-slim

RUN pip install --no-cache-dir pipenv==2024.0.1

WORKDIR /app

COPY Pipfile Pipfile.lock ./
RUN pipenv install --deploy --system

COPY . ./

RUN echo 'python /app/KubiScan.py $@' > /usr/local/bin/kubiscan && \
    chmod +x /usr/local/bin/kubiscan
