name: Docker Image

on: [workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ github.token }}
  FLEXIBITS_PAT: ${{ secrets.FLEXIBITS_PAT }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  IMAGE_REGISTRY: gcr.io
  IMAGE_OWNER: awesome-dogfish-208918
  IMAGE_NAME: kubiscan

jobs:
  container:
    name: Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Flexibits workflow
        uses: flexibits/github-actions/flexibits-setup@f088a6756133429d567ce6109c1660d7af7ca3de

      - name: Set $IMAGE
        uses: flexibits/github-actions/composite-image-name@f088a6756133429d567ce6109c1660d7af7ca3de

      - name: Build and push the container image
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile.flexibits
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE }}:latest
          cache-to: type=inline
