name: Docker Image

on: [workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ github.token }}
  FLEXIBITS_PAT: ${{ secrets.FLEXIBITS_PAT }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  IMAGE_REGISTRY: us-east1-docker.pkg.dev
  IMAGE_OWNER: awesome-dogfish-208918
  IMAGE_REPOSITORY: kubiscan
  IMAGE_NAME: kubiscan

jobs:
  container:
    name: Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Flexibits workflow
        uses: flexibits/github-actions/flexibits-setup@adaa7b70d85a371483b059d3a228cdff88eed50b

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set $IMAGE
        uses: flexibits/github-actions/composite-image-name@adaa7b70d85a371483b059d3a228cdff88eed50b

      - name: Build and push the container image
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile.flexibits
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
